apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-db
  template:
    metadata:
      labels:
        app: nexus-db
    spec:
      containers:
        - name: nexus-db
          image: mohamedashfaq/nexus-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
